# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: draggos-api

configValidationMode: error
frameworkVersion: "3"

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/draggos-${self:provider.stage}}
  SECRET_KEY: ${self:custom.secrets.SECRET_KEY}
  RPC_URL: ${self:custom.secrets.RPC_URL}
  INCUBATOR_PROGRAM_ID: ${self:custom.secrets.INCUBATOR_PROGRAM_ID}
  CANDY_MACHINE_ID: ${self:custom.secrets.CANDY_MACHINE_ID}
  HEADERS: ${self:custom.secrets.HEADERS}
  S3_BUCKET: ${cf:draggos-app-deployment-${self:provider.stage}.BuildBucket}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 30
  lambdaHashingVersion: "20201221"
  apiGateway:
    apiKeys:
      - Draggos-API-${opt:stage, 'dev'}
  tracing:
    lambda: true
  environment:
    S3_BUCKET: ${self:custom.S3_BUCKET}
    RPC_URL: ${self:custom.RPC_URL}
  iam:
    role:
      name: ${self:service}-${self:provider.stage}-role
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::${self:custom.S3_BUCKET}/metadata/*

functions:
  createMetadata:
    handler: tasks/createMetadata.handler
    environment:
      SECRET_KEY: ${self:custom.SECRET_KEY}
      INCUBATOR_PROGRAM_ID: ${self:custom.INCUBATOR_PROGRAM_ID}
    events:
      - http:
          path: mints/{mint}/metadata
          method: post
          private: true
          cors: true
