[programs.devnet]
incubator = "99S2c1t1rWiRN2sw8zEtyuwtbToqj7pZ9zuDha1N83o3"
controller = "4fLNdQ1L55KeCFS1Z82kLr2UkvxnDGQgs9jp7fQua7yR"

[programs.localnet]
incubator = "99S2c1t1rWiRN2sw8zEtyuwtbToqj7pZ9zuDha1N83o3"
controller = "4fLNdQ1L55KeCFS1Z82kLr2UkvxnDGQgs9jp7fQua7yR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/davidbarrick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
