[programs.devnet]
incubator = "ApvUM9JNBz1idd1MZ2E2YhYaFhPygkfoUY82fwEjwPFC"

[programs.localnet]
incubator = "ApvUM9JNBz1idd1MZ2E2YhYaFhPygkfoUY82fwEjwPFC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/davidbarrick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
