[programs.devnet]
incubator = "GJ285g95ZVgCKLhQUA6LYDzwqzQbgq3cR2GpsA5N1ChZ"

[programs.localnet]
incubator = "GJ285g95ZVgCKLhQUA6LYDzwqzQbgq3cR2GpsA5N1ChZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/davidbarrick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
