[programs.devnet]
incubator = "HKT5Mqxok4KBwYgqmSYd89MAY5FjBNokQqGGEjMDcg36"
controller = "7NGqArzJMzzvQQhbETSooJ3KA1CkVopxGmAWnAjHcSqi"

[programs.localnet]
incubator = "HKT5Mqxok4KBwYgqmSYd89MAY5FjBNokQqGGEjMDcg36"
controller = "7NGqArzJMzzvQQhbETSooJ3KA1CkVopxGmAWnAjHcSqi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/davidbarrick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
