[programs.devnet]
incubator = "2zmbDv3c8ni15u6LTt4mNDXu9NmQ6RfpgggpZ59DvP3T"
controller = "2QPGAb8c9gyZvYKg3kPbBLh4dtNWfWQQwjYdfKLCFMJo"

[programs.localnet]
incubator = "2zmbDv3c8ni15u6LTt4mNDXu9NmQ6RfpgggpZ59DvP3T"
controller = "2QPGAb8c9gyZvYKg3kPbBLh4dtNWfWQQwjYdfKLCFMJo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/davidbarrick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
